---
- block:
   - name: Install Apache
     ansible.builtin.apt:
       name: apache2

   - name : Start apache2 services
     ansible.builtin.service:
       name: apache2
       state: started
       enabled: true

       #   - name: Copy over index.html
       #ansible.builtin.template:
       #src: patch_list.j2 
       #dest: /var/www/html/index.html
       #owner: root
       #group: root
       #mode: 644
       # delegate_to: "{{ item }}"
       #loop: "{{ groups['web-servers']}}"
