---
- name: download promtail
  ansible.builtin.get_url:
          url: https://github.com/grafana/loki/releases/download/v3.2.0/promtail-linux-amd64.zip
          dest: /tmp/promtail-linux-amd64.zip

- name: unarchive promtail zip
  ansible.builtin.unarchive:
          src: /tmp/promtail-linux-amd64.zip
          remote_src: true
          dest: /usr/local/bin
          mode: 0554
          owner: promtail
          group: promtail

- name: copy config file for promtail
  ansible.builtin.copy:
          src: ./files/promtail.yaml
          dest: /etc/promtail/promtail.yaml
          owner: promtail
          group: promtail
          mode: 0544

- name: copy log rotate config
  ansible.builtin.copy:
          src: ./files/promtail_acl
          dest:  /etc/logrotate.d/promtail_acl
          owner: root
          group: root
          mode: 0544 

- name: set log acls
  ansible.builtin.shell: |
        /usr/bin/setfacl -R -m d:u:promtail:rx /var/log
        /usr/bin/setfacl -m u:promtail:rx /var/log
        /usr/bin/setfacl -R -m d:u:promtail:rx /var/log/audit
        /usr/bin/setfacl -m u:promtail:rx /var/log/audit
        /usr/bin/setfacl -m u:promtail:r /var/log/secure
        /usr/bin/setfacl -m u:promtail:r /var/log/audit/audit.log
        /usr/bin/setfacl -m u:promtail:r /var/log/dnf.log

- name: Copy the promtail unit file
  ansible.builtin.copy:
          src: ./files/promtail.service
          dest: /etc/systemd/system/promtail.service
          owner: root
          group: root
          mode: 0544

- name: Start promtail service
  ansible.builtin.systemd:
          daemon_reload: true
          name: promtail.service
          state: started
          enabled: true
