---
- name: download promtail
  ansible.builtin.get_url:
          url: "{{ promtail_url }}"
          dest: /tmp/promtail-linux-amd64.zip

- name: unarchive promtail zip
  ansible.builtin.unarchive:
          src: /tmp/promtail-linux-amd64.zip
          remote_src: true
          dest: /usr/local/bin
          mode: 0554
          owner: "{{ promtail_user }}"
          group: "{{ promtail_group }}"

- name: set config file for promtail
  ansible.builtin.template:
          src: promtail.yml.j2
          dest: "{{ promtail_config_folder }}/promtail.yaml"
          owner:  "{{ promtail_user }}"
          group:  "{{ promtail_group }}"
          mode: 0544

- name: Set log rotate config
  ansible.builtin.template:
          src: promtail_acl.j2
          dest:  /etc/logrotate.d/promtail_acl
          owner: root
          group: root
          mode: 0544 

- name: Set log acls for rhel
  ansible.builtin.shell: |
        /usr/bin/setfacl -R -m d:u:promtail:rx /var/log
        /usr/bin/setfacl -m u:promtail:rx /var/log
        /usr/bin/setfacl -m u:promtail:r /var/log/secure
        /usr/bin/setfacl -m u:promtail:r /var/log/dnf.log
        /usr/bin/setfacl -R -m d:u:promtail:rx /var/log/audit
        /usr/bin/setfacl -m u:promtail:rx /var/log/audit
        /usr/bin/setfacl -m u:promtail:r /var/log/audit/audit.log
  when: ansible_os_family == "RedHat"

- name: Set log acls for debian
  ansible.builtin.shell: |
        /usr/bin/setfacl -R -m d:u:promtail:rx /var/log
        /usr/bin/setfacl -m u:promtail:rx /var/log
        /usr/bin/setfacl -m u:promtail:r /var/log/secure
        /usr/bin/setfacl -m u:promtail:r /var/log/dnf.log
        /usr/bin/setfacl -m u:promtail:r /var/log/auth.log
  when: ansible_os_family == "Debian"     


- name: Set the promtail unit file
  ansible.builtin.template:
          src: promtail.service.j2
          dest: /etc/systemd/system/promtail.service
          owner: root
          group: root
          mode: 0544
  notify: Restart systemd

- name: Start promtail service
  ansible.builtin.systemd:
          name: promtail.service
          state: started
          enabled: true

