---
- name: Create promtail group
  ansible.builtin.group:
          name: promtail
          state: present
          system: true

- name: Create promtail user
  ansible.builtin.user:
          name: promtail
          group: promtail
          state: present
          system: true
          shell: /usr/sbin/nologin
          create_home: false

- name: Create promtail config folder
  ansible.builtin.file:
          path: /etc/promtail
          state: directory
          mode: 0755
          owner: promtail
          group: promtail

- name: Create promtail positions file
  ansible.builtin.file:
          path: /tmp/positions.yaml  
          state: touch
          mode: 0600
          owner: promtail
          group: promtail



