---
- name: Download loki zip file
  ansible.builtin.get_url:
          url: "{{ loki_url }}"
          dest: /tmp/loki-linux-amd64.zip

- name: Unarchive loki zip file
  ansible.builtin.unarchive:
          src: /tmp/loki-linux-amd64.zip
          dest: /usr/local/bin
          remote_src: true
          owner: "{{ loki_user }}"
          group: "{{ loki_group }}"
          mode: 0554

- name: Copy loki config file
  ansible.builtin.template:
          src: loki-local-config.yaml.j2
          dest: "{{ loki_config_file }}"
          owner: "{{ loki_user }}"
          group: "{{ loki_group }}"
          mode: 0644

- name: copy loki unit file
  ansible.builtin.template:
          src: loki.service.j2
          dest: /etc/systemd/system/loki.service
          owner: root
          group: root
          mode: 0644
  notify: Reload systemd

- name: Start loki service
  ansible.builtin.systemd:
          name: loki.service
          state: started
          enabled: true

