---
- name: Download node_exporter tar
  ansible.builtin.get_url:
        url: "{{node_exporter_url}}"
        dest: /tmp/node_exporter-1.8.2.linux-amd64.tar.gz
        checksum: sha256:6809dd0b3ec45fd6e992c19071d6b5253aed3ead7bf0686885a51d85c6643c66

- name: Unarchive node_exporter
  ansible.builtin.unarchive:
          src: /tmp/node_exporter-1.8.2.linux-amd64.tar.gz
          dest: /usr/local/bin
          remote_src: yes
          owner: "{{node_exporter_user}}"
          group: "{{node_exporter_group}}"
          mode: 0554
          include:
                 - node_exporter-1.8.2.linux-amd64/node_exporter
          extra_opts:
                  - --strip-components=1

- name: Copy node_exporter unit file
  ansible.builtin.template:
          src: ./templates/node_exporter.j2
          dest: /etc/systemd/system/node_exporter.service
  notify: Restart_systemd

- name: Restart systemd
  ansible.builtin.systemd:
          name: node_exporter.service
          enabled: true
          state: started
  notify: Smoketest

