---

- name : Create node_exporter group
  ansible.builtin.group:
         name: "{{ node_exporter_group }}"
         state: present


- name: Create node_exporter user
  ansible.builtin.user:
          name: "{{node_exporter_user}}"
          group: "{{node_exporter_group}}"
          shell: /usr/sbin/nologin 
          state: present

