---
- name: Download prometheus tar file
  ansible.builtin.get_url:
          url: "{{ prometheus_url }}"
          dest: /tmp/prometheus-2.54.0.linux-amd64.tar.gz
          checksum: sha256:465e1393a0cca9705598f6ffaf96ffa78d0347808ab21386b0c6aaec2cf7aa13

- name: Unarchive prometheus tar file
  ansible.builtin.unarchive:
          src: /tmp/prometheus-2.54.0.linux-amd64.tar.gz
          dest: /usr/local/bin
          remote_src: yes
          owner: "{{ prometheus_user }}"
          group: "{{ prometheus_group }}"
          mode: 0554
          include: 
               - prometheus-2.54.0.linux-amd64/prometheus
          extra_opts:
                  - --strip-components=1

- name: Copy prometheus scrape config
  ansible.builtin.template:
          src: ./templates/prometheus.j2
          dest: /etc/prometheus/prometheus.yml
          owner: "{{ prometheus_user }}"
          group: "{{ prometheus_group }}"
          mode: 0554
  notify: Restart_prom_service

- name: Copy prometheus unit file
  ansible.builtin.template:
          src: ./templates/prometheus.service.j2
          dest: /etc/systemd/system/prometheus.service
          owner: root
          group: root
          mode: 0644
  notify: Restart_systemd

- name: Start systemdctl and prom service
  ansible.builtin.systemd:
          name: prometheus.service
          state: restarted
          enabled: true

